version: "3.9"

services:
  web:
    build: .
    container_name: chsn-running
    ports:
      - "8000:8000"
    # Bind-mount your code so edits on your Mac reflect in the container.
    volumes:
      - .:/app
    # Override CMD for dev hot-reload inside the container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # If you later add env vars, you can uncomment:
    # env_file: .env

  # db (optional, for the /runs feature later)
  # db:
  #   image: postgres:15
  #   container_name: chsn-db
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: running
  #   ports:
  #     - "5432:5432"
