apiVersion: v1
kind: Service
metadata:
  name: chsn-running
  labels:
    app: chsn-running
spec:
  type: LoadBalancer
  selector:
    app: chsn-running
  ports:
    - name: http
      port: 80
      targetPort: 8000